### PR TITLE
Correct copyright

### PR DESCRIPTION
**Pull request by veelenga**
This PR simply corrects the copyright year. Should the copyright name be changed too now?

### CODE REVIEW

**Comment by richmolj** [comment]
Thanks @veelenga ❤️ !

The copyright should now be Lee Richmond if you don't mind 🙂

**Comment by veelenga** [comment]
Done 👍

**Comment by veelenga** [comment]
@richmolj do you know why tests fail?

**Comment by richmolj** [comment]
@veelenga it's entirely on me - will be cleaning things up this/next week and will make sure this gets in then!

**Comment by veelenga** [comment]
@richmolj  🏓

**Comment by richmolj** [comment]
@veelenga sorry for the delay, thanks again ❤️ !

**Pull request merged**
