### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by stevenharman**

### CODE REVIEW

**Comment by stevenharman** [comment]
@richmolj I'll squash these into a single commit once I've finished reading this doc. Wanted to note them as I hit them.

**Comment by richmolj** [comment]
Very much appreciated ❤️ ! I'll hold off merging so you don't have to keep re-opening a PR.

**Comment by stevenharman** [comment]
That's about all I have time for today. Feel free to merge when you like.

**Review by richmolj — APPROVED** [review]

**Comment by richmolj** [comment]
Thanks again! 👏

**Pull request merged**
