### PR TITLE
Fix specs

### PR DESCRIPTION
**Pull request by richmolj**

### CODE REVIEW

**Comment by richmolj** [comment]
@sideshowbandana this is absolutely fantastic. If you want to clean up the commits a bit, I'm ready to merge 🎉 ❤️

**Comment by sideshowbandana** [comment]
Thanks. Happy to do a clean up, but I'm unclear on what you'd like. Are you asking me to squash and force push? Or...?

**Comment by richmolj** [comment]
Yep - squash and force push into one nice commit would be great

**Comment by sideshowbandana** [comment]
Done

**Pull request merged**
