### PR TITLE
Use the endpoint_namespace when generating spec files for a resource

### PR DESCRIPTION
**Pull request by sideshowbandana**
If a user configures a different namespace, the generator should
create a spec file based on the defined namespace.

### CODE REVIEW

**Comment by richmolj** [comment]
This is great, just want to verify you tested with creating a new app (for instance the quickstart). In the past it's come up that since we're generating ApplicationResource in the same task we're referencing it things blow up.

**Comment by sideshowbandana** [comment]
> This is great, just want to verify you tested with creating a new app (for instance the quickstart). In the past it's come up that since we're generating ApplicationResource in the same task we're referencing it things blow up.

Verified. Generating specs with namespace set to /api/v2, will create files with the correct file and request paths.

**Comment by richmolj** [comment]
Thanks so much @sideshowbandana 👏  !

**Comment by mihaimuntenas** [comment]
No problem! Glad I could help!
Thank you for maintaining this fine gem! :heart:

**Pull request merged**
